# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SSpai' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'FTIndicator'
pod 'Kingfisher'
pod 'SwiftyJSON'
pod 'MJExtension'
#pod 'DZNEmptyDataSet'
pod 'Alamofire'
pod 'SnapKit'
pod 'MJRefresh'

end
